Results coming from the previous commit is added in this commit. According to the README, looks like it is working file till step 2.
In step 3, I am getting one file not found error (some community result file) and one index out of bound exception in CommunityResult::storeMetricInput(). Maybe it is coming from not getting the expected file?

java.io.FileNotFoundException: /Users/imranur/Research/LLM-for-package-clustering/ICSE19-GefDroid/GefDroid-Code/ICSE-2019/file/result/Community_Result.txt (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(Unknown Source)
        at java.base/java.io.FileInputStream.<init>(Unknown Source)
        at java.base/java.io.FileReader.<init>(Unknown Source)
        at AppSimilarityGraph.ComunityResult.readDataFromFile(ComunityResult.java:32)
        at Run.Preprocess.ConstructAppGraph.analyzeResult(ConstructAppGraph.java:186)
        at Run.Preprocess.ConstructAppGraph.main(ConstructAppGraph.java:37)
Im Node Size: 0
Fg Node Size: 0
Lp Node Size: 0
Ml Node Size: 0
Ground Truth Node Size: 10
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        at AppSimilarityGraph.ComunityResult.storeMetricInput(ComunityResult.java:156)
        at Run.Preprocess.ConstructAppGraph.analyzeResult(ConstructAppGraph.java:190)
        at Run.Preprocess.ConstructAppGraph.main(ConstructAppGraph.java:37)